### ISSUE TITLE
Consider moving away from yaserde

### ISSUE THREAD

**Issue by taiki-e** [openrr/urdf-rs#96]
We have switched to yaserde from serde-xml-rs in #64 (urdf-rs 0.7.0). However, many bugs have been introduced since then, some of which have not yet been fixed.

- https://github.com/openrr/urdf-rs/pull/74
- https://github.com/openrr/urdf-rs/pull/75
- https://github.com/openrr/urdf-rs/issues/80
- https://github.com/openrr/urdf-rs/issues/87
- https://github.com/openrr/urdf-rs/issues/94
- https://github.com/openrr/urdf-rs/issues/95
- default value of Axis::xyz accidentally changed to `[0, 0, 0]` from `[1, 0, 0]`
  - this caused https://github.com/openrr/urdf-viz/issues/256

I'm no longer happy with continuing to use this difficult-to-use crate.
I'm considering moving away from it, at least on deserialization.

Candidates for alternatives in my mind are serde-xml-rs, which was used previously, and [roxmltree](https://github.com/RazrFalcon/roxmltree), which is currently used in [mesh-loader](https://github.com/openrr/mesh-loader). We should not use anything we have no experience with or are not familiar with, like yaserde.
Both support deserialization only; as for serialization, we can continue to use yaserde, or we can consider replacing it with our own. Anyway, it is important to fix deserialization, which obviously has correctness problems.

FYI @luca-della-vedova

**Comment by luca-della-vedova** [comment]
I can see the frustration and I obviously feel partially guilty for this. I guess the only testing I did was to see if it works for my use cases and that it passed the pre-existing unit tests but that proved out to be insufficient since these don't really capture the wild variety of URDF files out there.

I'd like to try to look at these issues first but I will understand if you want to move away from `yaserde`. I suppose having `serde-xml-rs` and `yaserde` and having structures `[derive(Deserialize, YaSerialize)]` could bring the best of both worlds (robust deserialization and at least _some_ serialization support), but that would have the cost of having double the number of dependencies.
I'll ultimately leave the call up to you as the maintainer, happy to help whichever direction you choose to go.

**Comment by luca-della-vedova** [comment]
For reference I've been playing with removing `yaserde` in favor of `quick-xml` [here](https://github.com/luca-della-vedova/urdf-rs/tree/luca/quick_xml).
I reached the point where all the existing unit tests work (including serialization / deserialization round trip), but given the history I'll work on adding a regression test for every issue that has been opened, as well as trying to improve coverage, before really taking the result too seriously.
There is only one "minor" API breakage, I had to add another struct to wrap geometry as denoted [here](https://github.com/tafia/quick-xml/issues/699). I added a `Deref` and `DerefMut` implementation so the only user facing difference is adding a dereference operator when accessing geometry object, shown [here](https://github.com/openrr/urdf-rs/compare/main...luca-della-vedova:urdf-rs:luca/quick_xml?expand=1#diff-8d62bc36756983450bed637fcfc5baeca867b8d61e22a75057ab9c1180dfc85cL113-R108).

Do you think this exploration is OK or would you rather just revert to the previous option? For what it's worth on crates.io quick-xml has much more activity / downloads than serde-xml-rs, although I'll be honest I can't remember why I chose yaserde for the serialization implementation, this really just looks a lot better.
![image](https://github.com/openrr/urdf-rs/assets/9111558/c26a99c7-cf87-4ad1-a52a-ec084371d22a)

**Comment by taiki-e** [comment]
> For reference I've been playing with removing `yaserde` in favor of `quick-xml` [here](https://github.com/luca-della-vedova/urdf-rs/tree/luca/quick_xml).
> I reached the point where all the existing unit tests work (including serialization / deserialization round trip), but given the history I'll work on adding a regression test for every issue that has been opened, as well as trying to improve coverage, before really taking the result too seriously.
> There is only one "minor" API breakage, I had to add another struct to wrap geometry as denoted [here](https://github.com/tafia/quick-xml/issues/699). I added a `Deref` and `DerefMut` implementation so the only user facing difference is adding a dereference operator when accessing geometry object, shown [here](https://github.com/openrr/urdf-rs/compare/main...luca-della-vedova:urdf-rs:luca/quick_xml?expand=1#diff-8d62bc36756983450bed637fcfc5baeca867b8d61e22a75057ab9c1180dfc85cL113-R108).

Thanks! At first glance, it looks great to me. Being able to handle problematic cases is great, and not having to manually parse enums is also great.

And [this workaround](https://github.com/openrr/urdf-rs/pull/64/files#diff-8d62bc36756983450bed637fcfc5baeca867b8d61e22a75057ab9c1180dfc85cL6) that was necessary when serde-xml-rs was used is no longer needed?

**Comment by luca-della-vedova** [comment]
> And [this workaround](https://github.com/openrr/urdf-rs/pull/64/files#diff-8d62bc36756983450bed637fcfc5baeca867b8d61e22a75057ab9c1180dfc85cL6) that was necessary when serde-xml-rs was used is no longer needed?

No it is not necessary anymore. I believe that case is already captured by the unit tests since we check that all the joints and links are parsed correctly [here](https://github.com/openrr/urdf-rs/blob/e07b0ea013b47223213708a15430a2350c4ef02e/src/funcs.rs#L92-L93) but they are in order of "link-joint-link-link-joint" [here](https://github.com/openrr/urdf-rs/blob/e07b0ea013b47223213708a15430a2350c4ef02e/src/funcs.rs#L180-L229).
Specifically for this crate, there is a (default off, that I enabled) [feature](https://github.com/tafia/quick-xml/blob/de61fa1094dbeec0bb144568673ac719d9d359a6/Cargo.toml#L123-L168) to deal with non continuous lists, at the expense of extra parsing time.
